on:
  release:
    workflow_dispatch:
    types: [created]

jobs:
  release:
    name: Release Go Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.17.5
          dest: build
          pkg: cmd/clip
          prefix: clip
          targets: darwin/arm64,darwin/amd64,windows/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            README.md
            build/**
          tag_name: ${{ github.event.release.tag_name}}
